---
- hosts: localhost
  become: true

  vars:
    username: "vagrant"
    home: "/home/{{ username }}"
    document_root: "/{{ username }}"

  roles:
    - zsh
    - neovim

  tasks:
    - name: required packages installed
      apt:
        name="{{ item }}"
        state=present
        update_cache=yes
      with_items:
        - wget
        - git
        - curl
        - libc++-dev
        - cmake
        - g++
        - doxygen
